version: "3.0"
services:
  db:
    container_name: db
    image: mysql:8.1
    restart: always
    env_file:
      template.env
    ports:
      - "3306:3306"

  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      template.env
    ports:
      - '8080:80'

  goblog:
    build:
      context: .
      args:
        VERSION: develop
    image: compscidr/goblog:latest
    container_name: goblog
    depends_on:
      - db
    restart: always
    env_file:
      template.env
    ports:
      - "7000:7000"
    volumes:
      - ./template.env:/go/src/github.com/compscidr/goblog/local.env
      - ../:/var/www/html/
      - ${PWD}/test.db:/go/src/github.com/compscidr/goblog/test.db